version: '3.8'
services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - chatbot-net
    expose:
      - 8000

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - chatbot-net
    ports:
      - "80:80"

  ollama:
    build: ./ollama
    container_name: chatbot-ollama
    restart: unless-stopped
    networks:
      - chatbot-net
    expose:
      - 11434
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:

networks:
  chatbot-net:
    driver: bridge
