version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_started   # Changed from service_healthy to avoid long delays
    networks:
      - chatbot-net
    ports:
      - "8000:8000" # Accessible from host for testing

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - chatbot-net
    ports:
      - "80:80"

  ollama:
    build: ./ollama
    container_name: chatbot-ollama
    restart: unless-stopped
    networks:
      - chatbot-net
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:11434"]
      interval: 15s
      timeout: 5s
      retries: 20 # Allow longer for big model to load

volumes:
  ollama_data:

networks:
  chatbot-net:
    driver: bridge
