services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - chatbot-net
    ports:
      - "8000:8000"   # Changed from expose so you can test from host

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - chatbot-net
    ports:
      - "80:80"

  ollama:
    build: ./ollama
    container_name: chatbot-ollama
    restart: unless-stopped
    networks:
      - chatbot-net
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:

networks:
  chatbot-net:
    driver: bridge
